#= require lib/base.js.coffee
#= require lib/vm/page-content-viewmodel.js.coffee

do ->

    PageContentViewModel = require("lib.vm.PageContentViewModel")

    class Home extends PageContentViewModel
        constructor: ->
            super('views/home/home')

            # Hero Section
            @companyHeroImage = ko.observable("")
            @companyHeroHeader = ko.observable("")
            @companyHeroSubHeader = ko.observable("")
            @companyHeroButton = ko.observable("")

# ---
# generated by js2coffee 2.1.0
        prepDemo: ->
            # Hero Section
            @companyHeroImage("http://i.imgur.com/qB4Oq9Y.png")
            @companyHeroHeader("Empowered To Be Your Healthiest")
    define('vm.Home', Home)
